/*
 * 	Author: Murrie Battistoni Felipe
 * 	Created Date: 06/05/2020
 *  Description: migration of data into the table countryAreaCodes.
 */

 use utnphones;

INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 242', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 246', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 264', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 268', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 284', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 340', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 345', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 441', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 473', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 599', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 649', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 664', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 670', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 671', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 684', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 721', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 758', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 767', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 784', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 809', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 868', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 869', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('1 876', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('20', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('211', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('212', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('213', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('216', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('218', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('220', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('221', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('222', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('223', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('224', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('225', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('226', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('227', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('228', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('229', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('230', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('231', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('232', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('233', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('234', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('235', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('236', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('237', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('238', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('239', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('240', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('241', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('242', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('243', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('244', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('245', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('246', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('248', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('249', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('250', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('251', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('252', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('253', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('254', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('255', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('256', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('257', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('258', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('260', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('261', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('262', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('263', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('264', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('265', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('266', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('267', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('268', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('269', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('27', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('290', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('291', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('297', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('298', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('299', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('30', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('31', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('32', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('33', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('34', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('350', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('351', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('352', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('353', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('354', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('355', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('356', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('357', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('358', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('359', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('36', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('370', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('371', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('372', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('373', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('374', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('375', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('376', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('377', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('378', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('380', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('381', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('382', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('385', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('386', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('387', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('389', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('39', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('40', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('41', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('420', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('421', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('423', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('43', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('44', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('45', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('46', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('47', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('48', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('49', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('500', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('501', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('502', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('503', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('504', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('505', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('506', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('507', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('508', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('509', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('51', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('52', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('53', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('54', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('55', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('56', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('57', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('58', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('590', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('591', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('592', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('593', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('594', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('595', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('596', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('597', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('598', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('5999', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('60', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('61', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('62', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('63', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('64', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('65', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('66', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('670', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('672', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('673', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('674', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('675', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('676', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('677', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('678', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('679', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('680', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('681', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('682', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('683', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('685', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('686', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('687', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('688', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('689', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('690', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('691', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('692', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('7', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('81', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('82', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('84', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('850', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('852', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('853', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('855', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('856', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('86', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('870', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('880', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('886', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('90', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('91', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('92', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('93', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('94', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('95', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('960', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('961', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('962', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('963', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('964', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('965', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('966', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('967', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('968', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('970', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('971', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('972', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('973', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('974', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('975', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('976', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('977', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('98', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('992', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('993', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('994', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('995', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('996', 1);
INSERT INTO countryareacodes (code,idInterAreaCode) VALUES ('998', 1);